### ISSUE TITLE
Private key query

### ISSUE THREAD

**Issue by Boheswaran** [Danny-Engelman/ITpings#12]
Im new to LoRa and TTN. So can I ask a question ?
Is the private key similar to primary key?
By the way what is the ITPings_Key ?
Sorry if my questions are too basics. Guide me tho. Thank you in advanced.

**Comment by BhekinhlanhlaSiza** [comment]
Hello 
Were you able to work this issue out. I am stuck with the HTTP Integration, it gives me an error 
[04-Oct-2018 21:50:13 UTC] PHP Parse error:  syntax error, unexpected '?' in /home/explolcw/public_html/siza/ITpings_connector.php on line 264
